The solution of 'clickable' problem
LianaSimonian/Java_Level_01 pull request #40
Opened 2022-02-26 10:50 UTC by LianaSimonian

2022-02-26 13:30 UTC, gevorgyanarman requested changes

2022-02-26 13:30 UTC, gevorgyanarman commented on untitled1/src/main/com/aca/homework/week7/clickable/AbstractClickable.java
> +public abstract class AbstractClickable implements Clickable {
because the name field is common, let's keep it here and implement the name() method here too

2022-02-26 13:30 UTC, gevorgyanarman commented on untitled1/src/main/com/aca/homework/week7/clickable/Button.java
> +    public void click() {
you can implement the click method in the Abstract class too

2022-02-26 13:30 UTC, gevorgyanarman commented on untitled1/src/main/com/aca/homework/week7/clickable/Button.java
> +        return new Button(name, new Action() {
please do not hard-wire the action, instead, require it as a method argument

2022-02-26 13:30 UTC, gevorgyanarman commented on untitled1/src/test/com/aca/homework/week7/clickable/ClickableTest.java
> +            if (clickableObjectName.substring(0, 6).equals("button")) {
just use startsWith method of the String class

2022-02-26 22:13 UTC, LianaSimonian commented on untitled1/src/main/com/aca/homework/week7/clickable/AbstractClickable.java
> +    public AbstractClickable(Action action) {
why did  we separate AbstactClicable class, if we can do all this in Button and Image classes, what is the basic meaning of separating AbstactClickable class, the name Abstactclickable class  is "Abstract"clickable but it is not abstract, it is a bit confusing.

2022-03-05 11:00 UTC, gevorgyanarman requested changes

2022-03-05 11:00 UTC, gevorgyanarman commented on untitled1/src/test/com/aca/homework/week7/clickable/ClickableTest.java
> +        AbstractClickable[] clickables = new AbstractClickable[5];
let's keep an array of Clickables instead of AbstractClickable

2022-03-05 11:00 UTC, gevorgyanarman commented on untitled1/src/test/com/aca/homework/week7/clickable/ClickableTest.java
> +    public static void invokeClickAllObjects(AbstractClickable[] clickables) {
please use Clickable[] instead of AbstractClickable[]

2022-03-05 11:00 UTC, gevorgyanarman commented on untitled1/src/main/com/aca/homework/week7/clickable/Button.java
> +    public static Button ofButton(String name, Action action) {
the ofButton static factory method is not better than the constructor. so there is no need to create it

2022-03-10 08:06 UTC, gevorgyanarman requested changes

2022-03-10 08:06 UTC, gevorgyanarman commented on untitled1/src/test/com/aca/homework/week7/clickable/ClickableTest.java
> +        Clickable[] clickables = new AbstractClickable[5];
Clickable[] clickables = new Clickable[5];

2022-03-11 19:33 UTC, closed without merging